VAR_GLOBAL
    PressaoJusante : ST_InstrumentoAnalogico;
    TemperaturaOleo : ST_InstrumentoAnalogico;
    PIT700 : ST_InstrumentoAnalogico;
    PIT701 : ST_InstrumentoAnalogico;
    PIT702 : ST_InstrumentoAnalogico;
    PIT703 : ST_InstrumentoAnalogico;
    PIT704 : ST_InstrumentoAnalogico;
    PIT705 : ST_InstrumentoAnalogico;
    TIT700 : ST_InstrumentoAnalogico;
    TIT701 : ST_InstrumentoAnalogico;
    TIT702 : ST_InstrumentoAnalogico;
    TIT703 : ST_InstrumentoAnalogico;
    TIT704 : ST_InstrumentoAnalogico;
    MotorPrincipal : ST_Motor;
    MotorExaustor : ST_Motor;
    MotorVentilador1 : ST_Motor;
    MotorVentilador2 : ST_Motor;
    ValvulaSucao : ST_Valvula;
END_VAR
